### ISSUE TITLE
Allow setting the package name in PR title

### ISSUE THREAD

**Issue by rrueth** [dependencies-io/git-repos#11]
I was playing with the ability to maintain updates for Git dependencies (https://www.dependencies.io/docs/dependencies/git-repos/). I noticed that when I follow the directions on that page, a PR is generated with a title like:

> Update https://github.com/grafana/grafana in git_dependencies.yml from v6.1.3 to v6.1.4 

Instead of the URL, I'd prefer if the PR title contained the name of the dependency. For example:

> Update Grafana from v6.1.3 to v6.1.4 

For example, could there be a configuration option along the lines of `package_name: Grafana`? 

I used the following `git_repos.yml` generate this example:

```
repos:
  - url: https://github.com/grafana/grafana
    installed: v6.1.3
    replace_in_files:
      packer.json: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_{version_clean}_amd64.deb
```
