### ISSUE TITLE
Tag / semver detection is flawed

### ISSUE THREAD

**Issue by WarheadsSE** [dependencies-io/git-repos#8]
The viable tag detection used by default does not operate as expected. In addition to mis-matching what a "newer" version is, it can detect an entirely non-SemVer that somehow precedes viable tags.

**dependencies_io/git_repos.yaml**:

```YAML
repos:
    - url: https://github.com/docker/distribution.git
      installed: v2.7.1
      versions: L.Y.Y
      replace_in_files:
          values.yaml: "tag: '{version_clean}'"
```

**Expected:**

```
$ deps run
No updates found
```

**Actual:**

`from "v2.7.1" to "docs-v2.5.0-2016-07-28"`

```
$ deps run
Found 1 update for git_repos on dependencies_io/git_repos.yml
- `https://github.com/docker/distribution.git` in `dependencies_io/git_repos.yml` from "v2.7.1" to "docs-v2.5.0-2016-07-28"
```

**Workaround:**

Use a prefix of `v` to force tag recognition as _only_ `vX.Y.Z*` format, and remove `v` from the `installed` version.

```YAML
repos:
    - url: https://github.com/docker/distribution.git
      installed: 2.7.1
      versions: L.Y.Y
      prefix: "v"
      replace_in_files:
          values.yaml: "tag: '{version_clean}'"
```

**Probably cause:**

`collect.py` appends non-SemVer tags, as `# not semver so we have to include it as an option`. Somewhere between this and `act.py` being called, a completely inaccurate string is chosen in preference over the correct answer.
